resources:
- dep-globex-ui-unsigned.yaml

patches:
- target:
    kind: Deployment
    name: globex-ui-unsigned
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value:       "quay.apps.cluster-tr57n.tr57n.sandbox988.opentlc.com/quayadmin/globex-ui-unsigned:main-1bcb9836460f4ab5a8cef3b00477982294d057ee"