globex:
  registry:
    imageRepo: ""
    dockerConfigJson: ""
  gitea:
    manifestRepo: ""
    manifestFile: ""
    manifestFileProd: ""
    manifestRepoName: ""
    gitRepoHost: ""
    manifestFileFail: ""
    webhookSecretKey: ""
    token: ""
